version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - leaderboard-network

  app:
    build: .
    container_name: node-leaderboard
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - leaderboard-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  leaderboard-network:
    driver: bridge
